name: Test Cases

on:
  push:
    branches:
      - main

jobs:
  TestCases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '19'

      - name: Compile
        run: |
          cd $GITHUB_WORKSPACE/
          kotlinc -cp junit-4.13.1.jar TestCases.kt -include-runtime -d app.jar

      - name: Run Tests
        run: |
          java -cp app.jar:junit-4.13.1.jar org.junit.runner.JUnitCore TestCases.kt
