name: Test Cases

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '19'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Execute Tests
      run: java -jar build/libs/app.jar
