name: Test Cases

on:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '19'

    - name: Compile
      run: kotlinc TestCases.kt -include-runtime -d app.jar

    - name: Execute Tests
      run: java -jar app.jar
